<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="rrbot" params="parent prefix *origin">

    <!-- Constants for robot dimensions -->
    <xacro:property name="mass" value="1" />
    <!-- arbitrary value for mass -->
    <xacro:property name="width" value="0.1" />
    <!-- Square dimensions (widthxwidth) of beams -->
    <xacro:property name="base_link_length" value="2" />
    <!-- Link 1 -->
    <xacro:property name="link1_length" value="1" />
    <!-- Link 2 -->
    <xacro:property name="link2_length" value="1" />
    <!-- Link 3 -->
    <xacro:property name="link3_length" value="2.2" />
    <!-- Link 4 -->
    <xacro:property name="camera_link" value="0.05" />
    <!-- Size of square 'camera' box -->
    <xacro:property name="axel_offset" value="0.05" />
    <!-- Space btw top of beam and the each joint -->

    <joint name="${prefix}base_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${prefix}base_link" />
    </joint>

    <!-- Base Link -->
    <link name="${prefix}base_link">
      <collision>
        <origin xyz="0 0 ${base_link_length/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${width} ${width} ${base_link_length}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 ${base_link_length/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${width} ${width} ${base_link_length}"/>
        </geometry>
        <material name="orange"/>
      </visual>

      <inertial>
        <origin xyz="0 0 ${base_link_length/2}" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia ixx="${mass / 12.0 * (width*width + base_link_length*base_link_length)}" ixy="0.0" ixz="0.0" iyy="${mass / 12.0 * (base_link_length*base_link_length + width*width)}" iyz="0.0" izz="${mass / 12.0 * (width*width + width*width)}"/>
      </inertial>
    </link>

    <joint name="${prefix}joint1" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}link1"/>
      <origin xyz="0 0 ${base_link_length}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.7"/>
    </joint>

    <!-- Link 1 -->
    <link name="${prefix}link1">
      <collision>
        <origin xyz="${link1_length/2 - axel_offset} 0 ${axel_offset}" rpy="0 -1.5708 0"/>
        <geometry>
          <box size="${width} ${width} ${link1_length}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="${link1_length/2 - axel_offset} 0 ${axel_offset}" rpy="0 -1.5708 0"/>
        <geometry>
          <box size="${width} ${width} ${link1_length}"/>
        </geometry>
        <material name="yellow"/>
      </visual>

      <inertial>
        <origin xyz="${link1_length/2 - axel_offset} 0 ${axel_offset}" rpy="0 -1.5708 0"/>
        <mass value="${mass}"/>
        <inertia ixx="${mass / 12.0 * (width*width + link1_length*link1_length)}" ixy="0.0" ixz="0.0" iyy="${mass / 12.0 * (link1_length*link1_length + width*width)}" iyz="0.0" izz="${mass / 12.0 * (width*width + width*width)}"/>
      </inertial>
    </link>

    <joint name="${prefix}joint2" type="continuous">
      <parent link="${prefix}link1"/>
      <child link="${prefix}link2"/>
      <origin xyz="${link1_length - 2*axel_offset} 0 ${2*axel_offset}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.7"/>
    </joint>

    <!-- Link 2 -->
    <link name="${prefix}link2">
      <collision>
        <origin xyz="${link2_length/2 - axel_offset} 0 ${axel_offset}" rpy="0 -1.5708 0"/>
        <geometry>
          <box size="${width} ${width} ${link2_length}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="${link2_length/2 - axel_offset} 0 ${axel_offset}" rpy="0 -1.5708 0"/>
        <geometry>
          <box size="${width} ${width} ${link2_length}"/>
        </geometry>
        <material name="orange"/>
      </visual>

      <inertial>
        <origin xyz="${link2_length/2 - axel_offset} 0 ${axel_offset}" rpy="0 -1.5708 0"/>
        <mass value="${mass}"/>
        <inertia ixx="${mass / 12.0 * (width*width + link2_length*link2_length)}" ixy="0.0" ixz="0.0" iyy="${mass / 12.0 * (link2_length*link2_length + width*width)}" iyz="0.0" izz="${mass / 12.0 * (width*width + width*width)}"/>
      </inertial>
    </link>

    <joint name="${prefix}joint3" type="prismatic">
      <limit upper="${link3_length - 2*axel_offset}" lower="0" effort="50" velocity="10.0"/>
      <parent link="${prefix}link2"/>
      <child link="${prefix}link3"/>
      <origin xyz="${link2_length - axel_offset} 0 ${axel_offset}" rpy="3.1416 0 0"/>
      <axis xyz="0 0 -1"/>
      <dynamics damping="0.7"/>
    </joint>

    <!-- Link 3 -->
    <link name="${prefix}link3">
      <collision>
        <origin xyz="${axel_offset} 0 ${link3_length/2 - axel_offset}" rpy="0 0 0"/>
        <geometry>
          <box size="${width} ${width} ${link3_length}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="${axel_offset} 0 ${link3_length/2 - axel_offset}" rpy="0 0 0"/>
        <geometry>
          <box size="${width} ${width} ${link3_length}"/>
        </geometry>
        <material name="yellow"/>
      </visual>

      <inertial>
        <origin xyz="${axel_offset} 0 ${link3_length/2 - axel_offset}" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia ixx="${mass / 12.0 * (width*width + link2_length*link2_length)}" ixy="0.0" ixz="0.0" iyy="${mass / 12.0 * (link2_length*link2_length + width*width)}" iyz="0.0" izz="${mass / 12.0 * (width*width + width*width)}"/>
      </inertial>
    </link>

    <joint name="${prefix}tool_joint" type="fixed">
      <origin xyz="${axel_offset} 0 ${-link3_length + axel_offset}" rpy="0 0 0"/>
      <parent link="${prefix}link3"/>
      <child link="${prefix}tool_link" />
    </joint>


    <!-- Tool Link -->
    <link name="${prefix}tool_link">
    </link>
  </xacro:macro>

</robot>
